/**
 * Canonical metric catalog: keys, units, unit conversions, general-adult
 * reference ranges, and plausibility bounds.
 *
 * Ranges are GENERAL ADULT guidance for flagging only — the lab's own
 * printed range takes precedence when available, and nothing here is
 * medical advice. Values are always STORED in the canonical unit.
 */

export type RangeDirection = 'both' | 'high_bad' | 'low_bad'

export interface MetricDef {
  key: string
  label: string
  canonicalUnit: string
  /** unit string (lowercased) → multiply by this factor to get canonical. */
  acceptedUnits: Record<string, number>
  low?: number
  high?: number
  direction: RangeDirection
  /** Values outside these bounds are almost certainly extraction errors. */
  plausibleMin: number
  plausibleMax: number
}

const MG_DL_FROM_MMOL_GLUCOSE = 18.016
const MG_DL_FROM_MMOL_CHOL = 38.67
const MG_DL_FROM_MMOL_TRIG = 88.57

export const METRICS: MetricDef[] = [
  {
    key: 'glucose_fasting',
    label: 'Fasting glucose',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'mmol/l': MG_DL_FROM_MMOL_GLUCOSE },
    low: 70,
    high: 99,
    direction: 'both',
    plausibleMin: 20,
    plausibleMax: 700,
  },
  {
    key: 'glucose_pp',
    label: 'Post-prandial glucose',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'mmol/l': MG_DL_FROM_MMOL_GLUCOSE },
    high: 140,
    direction: 'high_bad',
    plausibleMin: 20,
    plausibleMax: 800,
  },
  {
    key: 'glucose_random',
    label: 'Random glucose',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'mmol/l': MG_DL_FROM_MMOL_GLUCOSE },
    high: 140,
    direction: 'high_bad',
    plausibleMin: 20,
    plausibleMax: 800,
  },
  {
    key: 'hba1c',
    label: 'HbA1c',
    canonicalUnit: '%',
    acceptedUnits: { '%': 1 },
    low: 4,
    high: 5.6,
    direction: 'high_bad',
    plausibleMin: 3,
    plausibleMax: 20,
  },
  {
    key: 'total_cholesterol',
    label: 'Total cholesterol',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'mmol/l': MG_DL_FROM_MMOL_CHOL },
    high: 200,
    direction: 'high_bad',
    plausibleMin: 50,
    plausibleMax: 600,
  },
  {
    key: 'ldl',
    label: 'LDL cholesterol',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'mmol/l': MG_DL_FROM_MMOL_CHOL },
    high: 100,
    direction: 'high_bad',
    plausibleMin: 10,
    plausibleMax: 400,
  },
  {
    key: 'hdl',
    label: 'HDL cholesterol',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'mmol/l': MG_DL_FROM_MMOL_CHOL },
    low: 40,
    high: 100,
    direction: 'low_bad',
    plausibleMin: 5,
    plausibleMax: 200,
  },
  {
    key: 'triglycerides',
    label: 'Triglycerides',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'mmol/l': MG_DL_FROM_MMOL_TRIG },
    high: 150,
    direction: 'high_bad',
    plausibleMin: 10,
    plausibleMax: 2000,
  },
  {
    key: 'bp_systolic',
    label: 'Blood pressure (systolic)',
    canonicalUnit: 'mmHg',
    acceptedUnits: { mmhg: 1 },
    low: 90,
    high: 120,
    direction: 'both',
    plausibleMin: 50,
    plausibleMax: 260,
  },
  {
    key: 'bp_diastolic',
    label: 'Blood pressure (diastolic)',
    canonicalUnit: 'mmHg',
    acceptedUnits: { mmhg: 1 },
    low: 60,
    high: 80,
    direction: 'both',
    plausibleMin: 30,
    plausibleMax: 160,
  },
  {
    key: 'hemoglobin',
    label: 'Hemoglobin',
    canonicalUnit: 'g/dL',
    acceptedUnits: { 'g/dl': 1, 'g/l': 0.1 },
    low: 12,
    high: 17.5,
    direction: 'both',
    plausibleMin: 3,
    plausibleMax: 25,
  },
  {
    key: 'wbc',
    label: 'White blood cells',
    canonicalUnit: '10³/µL',
    acceptedUnits: {
      '10³/µl': 1,
      '10^3/µl': 1,
      '10^3/ul': 1,
      'x10³/µl': 1,
      'thousand/µl': 1,
      '/cumm': 0.001,
      '/µl': 0.001,
      'cells/µl': 0.001,
    },
    low: 4,
    high: 11,
    direction: 'both',
    plausibleMin: 0.1,
    plausibleMax: 200,
  },
  {
    key: 'platelets',
    label: 'Platelets',
    canonicalUnit: '10³/µL',
    acceptedUnits: {
      '10³/µl': 1,
      '10^3/µl': 1,
      '10^3/ul': 1,
      'lakh/cumm': 100,
      '/cumm': 0.001,
      '/µl': 0.001,
    },
    low: 150,
    high: 450,
    direction: 'both',
    plausibleMin: 5,
    plausibleMax: 2000,
  },
  {
    key: 'rbc',
    label: 'Red blood cells',
    canonicalUnit: '10⁶/µL',
    acceptedUnits: { '10⁶/µl': 1, '10^6/µl': 1, '10^6/ul': 1, 'million/µl': 1, 'million/cumm': 1 },
    low: 4.2,
    high: 6.1,
    direction: 'both',
    plausibleMin: 1,
    plausibleMax: 10,
  },
  {
    key: 'tsh',
    label: 'TSH',
    canonicalUnit: 'µIU/mL',
    acceptedUnits: { 'µiu/ml': 1, 'uiu/ml': 1, 'miu/l': 1 },
    low: 0.4,
    high: 4.5,
    direction: 'both',
    plausibleMin: 0.01,
    plausibleMax: 100,
  },
  {
    key: 'free_t4',
    label: 'Free T4',
    canonicalUnit: 'ng/dL',
    acceptedUnits: { 'ng/dl': 1, 'pmol/l': 1 / 12.87 },
    low: 0.8,
    high: 1.8,
    direction: 'both',
    plausibleMin: 0.1,
    plausibleMax: 10,
  },
  {
    key: 'vitamin_d',
    label: 'Vitamin D (25-OH)',
    canonicalUnit: 'ng/mL',
    acceptedUnits: { 'ng/ml': 1, 'nmol/l': 1 / 2.496 },
    low: 30,
    high: 100,
    direction: 'low_bad',
    plausibleMin: 1,
    plausibleMax: 300,
  },
  {
    key: 'vitamin_b12',
    label: 'Vitamin B12',
    canonicalUnit: 'pg/mL',
    acceptedUnits: { 'pg/ml': 1, 'pmol/l': 1.355 },
    low: 200,
    high: 900,
    direction: 'low_bad',
    plausibleMin: 20,
    plausibleMax: 5000,
  },
  {
    key: 'creatinine',
    label: 'Creatinine',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'µmol/l': 1 / 88.4, 'umol/l': 1 / 88.4 },
    low: 0.6,
    high: 1.35,
    direction: 'high_bad',
    plausibleMin: 0.1,
    plausibleMax: 20,
  },
  {
    key: 'urea',
    label: 'Blood urea',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'mmol/l': 6.006 },
    low: 15,
    high: 40,
    direction: 'high_bad',
    plausibleMin: 2,
    plausibleMax: 300,
  },
  {
    key: 'uric_acid',
    label: 'Uric acid',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'µmol/l': 1 / 59.48, 'umol/l': 1 / 59.48 },
    low: 3.5,
    high: 7.2,
    direction: 'both',
    plausibleMin: 0.5,
    plausibleMax: 25,
  },
  {
    key: 'alt_sgpt',
    label: 'ALT (SGPT)',
    canonicalUnit: 'U/L',
    acceptedUnits: { 'u/l': 1, 'iu/l': 1 },
    high: 56,
    direction: 'high_bad',
    plausibleMin: 1,
    plausibleMax: 5000,
  },
  {
    key: 'ast_sgot',
    label: 'AST (SGOT)',
    canonicalUnit: 'U/L',
    acceptedUnits: { 'u/l': 1, 'iu/l': 1 },
    high: 40,
    direction: 'high_bad',
    plausibleMin: 1,
    plausibleMax: 5000,
  },
  {
    key: 'alp',
    label: 'Alkaline phosphatase',
    canonicalUnit: 'U/L',
    acceptedUnits: { 'u/l': 1, 'iu/l': 1 },
    low: 44,
    high: 147,
    direction: 'high_bad',
    plausibleMin: 5,
    plausibleMax: 3000,
  },
  {
    key: 'bilirubin_total',
    label: 'Total bilirubin',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'µmol/l': 1 / 17.1, 'umol/l': 1 / 17.1 },
    high: 1.2,
    direction: 'high_bad',
    plausibleMin: 0.05,
    plausibleMax: 50,
  },
  {
    key: 'sodium',
    label: 'Sodium',
    canonicalUnit: 'mEq/L',
    acceptedUnits: { 'meq/l': 1, 'mmol/l': 1 },
    low: 135,
    high: 145,
    direction: 'both',
    plausibleMin: 100,
    plausibleMax: 180,
  },
  {
    key: 'potassium',
    label: 'Potassium',
    canonicalUnit: 'mEq/L',
    acceptedUnits: { 'meq/l': 1, 'mmol/l': 1 },
    low: 3.5,
    high: 5.1,
    direction: 'both',
    plausibleMin: 1,
    plausibleMax: 10,
  },
  {
    key: 'calcium',
    label: 'Calcium',
    canonicalUnit: 'mg/dL',
    acceptedUnits: { 'mg/dl': 1, 'mmol/l': 4.008 },
    low: 8.6,
    high: 10.3,
    direction: 'both',
    plausibleMin: 4,
    plausibleMax: 20,
  },
  {
    key: 'ferritin',
    label: 'Ferritin',
    canonicalUnit: 'ng/mL',
    acceptedUnits: { 'ng/ml': 1, 'µg/l': 1, 'ug/l': 1 },
    low: 20,
    high: 250,
    direction: 'both',
    plausibleMin: 1,
    plausibleMax: 5000,
  },
  {
    key: 'esr',
    label: 'ESR',
    canonicalUnit: 'mm/hr',
    acceptedUnits: { 'mm/hr': 1, 'mm/1st hr': 1 },
    high: 20,
    direction: 'high_bad',
    plausibleMin: 0,
    plausibleMax: 150,
  },
  {
    key: 'crp',
    label: 'CRP',
    canonicalUnit: 'mg/L',
    acceptedUnits: { 'mg/l': 1, 'mg/dl': 10 },
    high: 10,
    direction: 'high_bad',
    plausibleMin: 0,
    plausibleMax: 500,
  },
]

export const METRIC_BY_KEY = new Map(METRICS.map((m) => [m.key, m]))

export function normalizeUnit(def: MetricDef, value: number, unit: string): number | null {
  const factor = def.acceptedUnits[unit.trim().toLowerCase()]
  if (factor === undefined) return null
  return value * factor
}
